apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  redis-host: {{ .Values.redis.host | b64enc }}
  redis-port: {{ .Values.redis.port | toString | b64enc }}
  redis-db: {{ .Values.redis.db | toString | b64enc }}
  redis-password: {{ .Values.redis.password_base64 }}
