# Default values for goapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: maclarensg/goapi
  tag: latest
  pullPolicy: Always

namespace: goapi

service:
  name: goapi
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - goapi.localdev.me

redis:
  host: redis
  port: 6379
  db: 0
  password_base64: "bXlzZWNyZXRwYXNzd29yZA=="

ingressEnabled: true
