name: Run Build and Push to Dockerhub

on:
  pull_request:
    branches:
      - main

jobs:  
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
   
    ## Builds our docker image!
    - name: Build the Docker image
      run: docker build . -t maclarensg/goapi:latest -t maclarensg/goapi:${{ github.sha }}

    ## Publishes our image to Docker Hub 😎
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        ## the name of our image
        name: maclarensg/goapi:${{ github.sha }}
        ## Here we pass in our Docker Username
        username: ${{ secrets.DOCKER_USERNAME }}
        ## and our Docker password which 
        password: ${{ secrets.DOCKER_PASSWORD }}