name: Package and Upload Helm Chart as GitHub Release Asset

on:
  release:
    types: [created]

jobs:
  chart:
    name: Release Chart
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          CHART_VERSION=$(echo ${ github.ref} | sed 's/refs\/tags\///')
          helm package ${CHART_PATH} --version=${CHART_VERSION}
      
      - name: Upload helm package
        uses: action/upload-artifact@v2
        with:
          path: /home/runner/work/goapi/goapi