name: Package and Upload Helm Chart as GitHub Release Asset

on:
  release:
    types: [created]

env:
  CHART_NAME: goapi
  CHART_PATH: ./charts/goapi

jobs:
  build:
    name: Build release helm
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Package Helm Chart
        run: |
          CHART_VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          echo "Chart version: $CHART_VERSION"
          helm package ${CHART_PATH} --version=${CHART_VERSION}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./${CHART_NAME}-${CHART_VERSION}.tgz 
          asset_name: ${CHART_NAME}-${CHART_VERSION}.tgz 
          asset_content_type: application/octet-stream


