name: Package and Upload Helm Chart as GitHub Release Asset

on:
  release:
    types: [created]

env:
  CHART_NAME: goapi
  CHART_PATH: ./helm/goapi

jobs:
  package_and_upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Set Chart Version
      run: |
        echo "CHART_VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')" >> $GITHUB_ENV
        echo "Chart version: $CHART_VERSION"

    - name: Package Helm Chart
      run: |
        helm package ${CHART_PATH} --version=${CHART_VERSION}

    - name: Upload Helm Chart as GitHub Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./goapi-${CHART_VERSION}.tgz
        asset_name: goapi-${CHART_VERSION}.tgz
        asset_content_type: application/gzip
        api_key: ${{ secrets.GITHUB_TOKEN }}